name: docs links on anbox-cloud.io/docs

on:
  schedule:
    - cron: "0 13 * * *"

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Write linkchecker config file
        run: |
          mkdir -p ~/.linkchecker
          cp scripts/linkcheckerrc ~/.linkchecker/

      - name: Run linkchecker
        continue-on-error: true
        run: linkchecker https://anbox-cloud.io/docs > ~/.linkchecker/linkchecker-out.txt

      - name: Parse linkchecker output
        run: scripts/parseDocsLinkcheckerOutput

      - name: Send message on failure
        if: failure()
        run: |
          curl -X POST \
          -F "workflow=${GITHUB_WORKFLOW}" \
          -F "repo_name=${GITHUB_REPOSITORY}" \
          -F "action_id=${GITHUB_RUN_ID}" \
          ${{ secrets.BOT_URL }}?room=docs
